### PR TITLE
update: PA state psychiatric

### PR DESCRIPTION
**Pull request by nmmarquez**
Add in PA psych fac data with addresses

### CODE REVIEW

**Review by hjohns12 — CHANGES_REQUESTED** [review]
Could you make the facility names slightly more descriptive, maybe like "X STATE HOSPITAL"? I worry these are too short to be easily google-able

**Comment by nmmarquez** [comment]
> Could you make the facility names slightly more descriptive, maybe like "X STATE HOSPITAL"? I worry these are too short to be easily google-able

yup yup good point!

**Review by erika-tyagi — APPROVED** [review]
Lgtm, thanks!

**Comment by erika-tyagi** [comment]
@nmmarquez - Just realized I made merge conflicts for you by updating the files on the main branch a few times since you opened this, sorry! Pls don't hate me, but could you pull the latest files from from `master` and re-run the script before adding these updates?

**Pull request closed without merging**
