### PR TITLE
feat: new fac_sheet restruecture

### PR DESCRIPTION
**Pull request by nmmarquez**
Moving @mceverett8 changes to a PR with reviews. It looks like we should do some name harmonization and agreement about how to deal with paths.

### CODE REVIEW

**Comment by nmmarquez** [comment]
1) There doesnt appear to be ids in here and I know that is intended to be part of the new automatic pipeline per @hjohns12 and @erika-tyagi document regarding the topic. Is that something that will come later or should we do it before merging?

**Comment by erika-tyagi** [comment]
> 1. There doesnt appear to be ids in here and I know that is intended to be part of the new automatic pipeline per @hjohns12 and @erika-tyagi document regarding the topic. Is that something that will come later or should we do it before merging?

I vote before merging! I can do that now. I don't think we should merge this into master until we can successfully build barstools off this branch. I added some stuff to this issue awhile ago that might need to be updated: https://github.com/uclalawcovid19behindbars/behindbarstools/issues/34

**Comment by erika-tyagi** [comment]
Collating my thoughts and questions here for now! 

General questions: Will these have downstream consequences? 
* Can we clean state names in `fac_spellings` (Abroad, DC, Deleware, Federal, NA) or update [`is_valid_state`](https://github.com/uclalawcovid19behindbars/behindbarstools/blob/master/R/is_valid_state.R)?
* Can we drop perfect duplicates in `fac_spellings`? 
* Should variable names be: lowercase w/ underscore? camelcase with period? something else? 
* Can we rename `Count.ID` to `Facility.ID`? 
* Do we need `jurisdiction` in `fac_spellings`? 

Variable-specific questions: 
* `age`: Can we replace with `Adult`, `Juvenile`, `Mixed` instead of `A`, `J`, `B` to be more explicit?  
* `security`: Do we no longer want to use HIFLD to populate this? 
* `current`: Given that this changes frequently, do we have a process for maintaining this? 

TODO: 
* Remove duplicates from `fac_info` (Michael) 
* Add ID to `fac_info` and `fac_spellings` (Erika) 
* QC `fac_info` and `fac_spellings` (Erika / All) 
* Update `barstools` given new crosswalk variable names, file paths, etc. (Erika)

**Comment by nmmarquez** [comment]
**general_note** if facility raw name is not there our system should not fail we should use the raw name as the presentation name on the website

> Collating my thoughts and questions here for now!
> 
> General questions: Will these have downstream consequences?
> 
>     * Can we clean state names in `fac_spellings` (Abroad, DC, Deleware, Federal, NA) or update [`is_valid_state`](https://github.com/uclalawcovid19behindbars/behindbarstools/blob/master/R/is_valid_state.R)?

Michael has done 

>     * Can we drop perfect duplicates in `fac_spellings`?

Should be double checked with a function this should be a repeat process 

>     * Should variable names be: lowercase w/ underscore? camelcase with period? something else? 

Camel  Case and period acronymns should always be all caps


>     * Can we rename `Count.ID` to `Facility.ID`?

yes!


>     * Do we need `jurisdiction` in `fac_spellings`?

no but it should have an is_federal section which indicates whether it is part of the special federal type merging which only relies on names. We also need to update the barstools package for this update

>     * For the new domain-relevant fields (e.g. `description`, `age`, `gender`, `security`, `diff_operator`, etc.) it should be the responsibility of the person adding new entries to populate this, right? Should we have a process for retroactively filling in missing data?

Should be done manual retrospectively

> 
> Variable-specific questions:
> 
>     * `age`: Can we replace with `Adult`, `Juvenile`, `Mixed` instead of `A`, `J`, `B` to be more explicit?
> 
>     * `security`: Do we no longer want to use HIFLD to populate this?
> 
>     * `current`: Given that this changes frequently, do we have a process for maintaining this?
> 
>     * `diff_operator_dummy`: The description says {Different Operator, Unknown} - should NA values be Unknown?
> 
>     * `diff_operator_dummy` / `diff_operator`: Can we consolidate these fields into one? With maybe a generic "Third-Party" or something for cases where we know there's a different operator, but we don't know who it is?
> 
>     * `source_population` / `source_capacity`: Are there other values besides HIFLD or public records?

General notes. Unknown should be converted to NA. `diff_operator_dummy` conveted to `is_diff_operator` and as 0/1 binary which will be done by @mceverett8 dont use HIFLD to update security cause our designations are better. and we should drop the current column. General notes we should have checks in booth the google sheets and within R

> 
> To-do before merging into master:
> 
>     * Remove duplicates from `fac_info` (Michael)
> 
>     * Add ID to `fac_info` and `fac_spellings` (Erika)
> 
>     * QC `fac_info` and `fac_spellings` (Erika / All)
> 
>     * Update `barstools` given new crosswalk variable names, file paths, etc. (Erika)
> 
> 
> Longer-term (I'll eventually turn these into separate issues):
> 
>     * Populate existing facilities with missing HIFLD IDs where possible
> 
>     * Geocode existing facilities with missing coordinates
> 
>     * Delete and/or find matches for the ~1400 facilities in `fac_spellings` without matches in `fac_data`?

**Review by hjohns12 — CHANGES_REQUESTED** [review]
Out of pure laziness, can we change the names in `fac_spellings` back to the old ones? 

`Name.Raw` = `facility_name_raw`
`Name.Clean` = `facility_name_clean`

**Review by hjohns12 — APPROVED** [review]
Looks good!

**Comment by erika-tyagi** [comment]
Sorry, last few questions: 
1. We talked about renaming `Population` to something like `Population.Feb20` to distinguish between this and `Residents.Population` picked up from the scrapers - do we want to do that? 
2. We dropped the `Website` variable in this process, I sort of like keeping it because (1) it can be helpful in figuring out whether two facilities are the same or not / what jurisdiction they fall under, (2) it can serve as a source / jog our memory on where a facility came from, and (3) we can get it from HIFLD. But super open to being overruled! 
3. I know we decided against including `Address` (which was also dropped in this process), but I'm having second thoughts since (1) it's one of the variables we've been including on [the main Google Sheet](https://docs.google.com/spreadsheets/d/1X6uJkXXS-O6eePLxw2e4JeRtM41uPZ2eRcOA_HkPVTk/edit#gid=1197647409) (and minimizing disruptions here seems good), (2) it's really useful for geocoding, (3) it's also helpful for figuring out if two facilities are the same or not, and (4) we can get it from HIFLD. Again, very open to being overruled, but wanted to ask the group!

**Comment by hjohns12** [comment]
> 1. We talked about renaming `Population` to something like `Population.Feb20` to distinguish between this and `Residents.Population` picked up from the scrapers - do we want to do that?

Yes, I think that's a good idea! I always forget about `Residents.Population`. 

> 2. We dropped the `Website` variable in this process, I sort of like keeping it because (1) it can be helpful in figuring out whether two facilities are the same or not / what jurisdiction they fall under, (2) it can serve as a source / jog our memory on where a facility came from, and (3) we can get it from HIFLD. But super open to being overruled!

Agree that we should keep this.

> 3. I know we decided against including `Address` (which was also dropped in this process), but I'm having second thoughts since (1) it's one of the variables we've been including on [the main Google Sheet](https://docs.google.com/spreadsheets/d/1X6uJkXXS-O6eePLxw2e4JeRtM41uPZ2eRcOA_HkPVTk/edit#gid=1197647409) (and minimizing disruptions here seems good), (2) it's really useful for geocoding, (3) it's also helpful for figuring out if two facilities are the same or not, and (4) we can get it from HIFLD. Again, very open to being overruled, but wanted to ask the group!

Down to keep address in there for the reasons you mentioned!

**Comment by mceverett8** [comment]
We talked about renaming Population to something like Population.Feb20 to distinguish between this and Residents.Population picked up from the scrapers - do we want to do that?

**Totally fine with this!** 

We dropped the Website variable in this process, I sort of like keeping it because (1) it can be helpful in figuring out whether two facilities are the same or not / what jurisdiction they fall under, (2) it can serve as a source / jog our memory on where a facility came from, and (3) we can get it from HIFLD. But super open to being overruled!

**Totally fine with this also! One thing to note is the HIFLD website variable is I think different from what we imagined what this variable originally would be. Originally I thought the website variable was to post the links for where we are getting our numbers for the facility which may not be on the main info page for each jurisdiction posted on HIFLD. Fine with either as our website variable though.**

I know we decided against including Address (which was also dropped in this process), but I'm having second thoughts since (1) it's one of the variables we've been including on the main Google Sheet (and minimizing disruptions here seems good), (2) it's really useful for geocoding, (3) it's also helpful for figuring out if two facilities are the same or not, and (4) we can get it from HIFLD. Again, very open to being overruled, but wanted to ask the group!

**Also down to keep address in there!**

**Comment by erika-tyagi** [comment]
> We talked about renaming Population to something like Population.Feb20 to distinguish between this and Residents.Population picked up from the scrapers - do we want to do that?
> 
> **Totally fine with this!**
> 
> We dropped the Website variable in this process, I sort of like keeping it because (1) it can be helpful in figuring out whether two facilities are the same or not / what jurisdiction they fall under, (2) it can serve as a source / jog our memory on where a facility came from, and (3) we can get it from HIFLD. But super open to being overruled!
> 
> **Totally fine with this also! One thing to note is the HIFLD website variable is I think different from what we imagined what this variable originally would be. Originally I thought the website variable was to post the links for where we are getting our numbers for the facility which may not be on the main info page for each jurisdiction posted on HIFLD. Fine with either as our website variable though.**
> 
> I know we decided against including Address (which was also dropped in this process), but I'm having second thoughts since (1) it's one of the variables we've been including on the main Google Sheet (and minimizing disruptions here seems good), (2) it's really useful for geocoding, (3) it's also helpful for figuring out if two facilities are the same or not, and (4) we can get it from HIFLD. Again, very open to being overruled, but wanted to ask the group!
> 
> **Also down to keep address in there!**

Sounds good! @mceverett8 Do you mind re-generating the two data sheets adding `Website` and `Address` back in? I can take care of renaming `Population`, adding in the IDs, and updating the documentation accordingly.

**Comment by mceverett8** [comment]
Happy to! @erika-tyagi

**Comment by mceverett8** [comment]
To confirm, do we want to use the old websites (that are supposed to have the source of covid data) we had in the original facility sheet to fill in 'Website' or do we want to use the general links from HIFLD? Happy to use either! @erika-tyagi

**Comment by erika-tyagi** [comment]
> To confirm, do we want to use the old websites (that are supposed to have the source of covid data) we had in the original facility sheet to fill in 'Website' or do we want to use the general links from HIFLD? Happy to use either! @erika-tyagi

Maybe do it hierarchically like with the other HIFLD data? So if we added a website w/ the COVID data source, use that. If not, use the general website from HIFLD?

**Review by erika-tyagi — APPROVED** [review]

**Pull request merged**
